"""Add configuraciones_notificaciones table

Revision ID: bc964be15d45
Revises: 
Create Date: 2025-06-29 20:33:58.597764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bc964be15d45'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adjuntos', 'tipo_documento',
               existing_type=mysql.ENUM('SOLICITUD', 'COMPROBANTE', 'FACTURA', 'OTRO'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'OTRO'"))
    op.alter_column('adjuntos', 'fecha_carga',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('fk_adjuntos_misiones_idx'), table_name='adjuntos')
    op.drop_index(op.f('fk_adjuntos_usuarios_idx'), table_name='adjuntos')
    op.create_index(op.f('ix_adjuntos_id_adjunto'), 'adjuntos', ['id_adjunto'], unique=False)
    op.drop_constraint(op.f('fk_adjuntos_misiones'), 'adjuntos', type_='foreignkey')
    op.create_foreign_key(None, 'adjuntos', 'misiones', ['id_mision'], ['id_mision'])
    op.drop_table_comment(
        'adjuntos',
        existing_comment='Archivos de soporte para las misiones',
        schema=None
    )
    op.alter_column('configuraciones_general', 'smtp_seguridad',
               existing_type=mysql.ENUM('none', 'tls', 'ssl', collation='utf8mb4_general_ci'),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'tls'"))
    op.create_index(op.f('ix_configuraciones_general_id_configuracion_general'), 'configuraciones_general', ['id_configuracion_general'], unique=False)
    op.alter_column('configuraciones_sistema', 'tipo_dato',
               existing_type=mysql.ENUM('STRING', 'NUMBER', 'BOOLEAN', 'JSON'),
               type_=sa.String(length=20),
               nullable=True,
               existing_server_default=sa.text("'STRING'"))
    op.alter_column('configuraciones_sistema', 'es_modificable',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.create_index(op.f('ix_configuraciones_sistema_id_configuracion'), 'configuraciones_sistema', ['id_configuracion'], unique=False)
    op.drop_table_comment(
        'configuraciones_sistema',
        existing_comment='Configuraciones globales del sistema (límites, tarifas, etc.)',
        schema=None
    )
    op.alter_column('estados_flujo', 'es_estado_final',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='Indica si es un estado terminal del flujo',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('estados_flujo', 'requiere_comentario',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='Si requiere comentario obligatorio al cambiar a este estado',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('estados_flujo', 'orden_flujo',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Orden secuencial en el flujo normal',
               existing_nullable=True)
    op.alter_column('estados_flujo', 'tipo_flujo',
               existing_type=mysql.ENUM('VIATICOS', 'CAJA_MENUDA', 'AMBOS'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'AMBOS'"))
    op.create_index(op.f('ix_estados_flujo_id_estado_flujo'), 'estados_flujo', ['id_estado_flujo'], unique=False)
    op.drop_table_comment(
        'estados_flujo',
        existing_comment='Estados del ciclo de vida de una misión oficial',
        schema=None
    )
    op.alter_column('gestiones_cobro', 'numero_gestion',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='Número único de la gestión de cobro',
               existing_nullable=False)
    op.alter_column('gestiones_cobro', 'fecha_generacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('gestiones_cobro', 'estado',
               existing_type=mysql.ENUM('PENDIENTE', 'EN_PROCESO', 'COMPLETADA', 'ANULADA'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDIENTE'"))
    op.drop_index(op.f('fk_gestiones_usuarios_idx'), table_name='gestiones_cobro')
    op.create_index(op.f('ix_gestiones_cobro_id_gestion_cobro'), 'gestiones_cobro', ['id_gestion_cobro'], unique=False)
    op.drop_constraint(op.f('fk_gestiones_misiones'), 'gestiones_cobro', type_='foreignkey')
    op.create_foreign_key(None, 'gestiones_cobro', 'misiones', ['id_mision'], ['id_mision'])
    op.drop_table_comment(
        'gestiones_cobro',
        existing_comment='Gestiones de cobro generadas por Tesorería',
        schema=None
    )
    op.alter_column('historial_flujo', 'tipo_accion',
               existing_type=mysql.ENUM('APROBAR', 'RECHAZAR', 'DEVOLVER', 'SUBSANAR', 'CREAR', 'MODIFICAR'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('historial_flujo', 'fecha_accion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('historial_flujo', 'datos_adicionales',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='Información adicional de la acción en formato JSON',
               existing_nullable=True)
    op.drop_index(op.f('fk_historial_flujo_estado_nuevo_idx'), table_name='historial_flujo')
    op.drop_index(op.f('fk_historial_flujo_misiones_idx'), table_name='historial_flujo')
    op.drop_index(op.f('fk_historial_flujo_usuarios_idx'), table_name='historial_flujo')
    op.drop_index(op.f('idx_fecha_accion'), table_name='historial_flujo')
    op.create_index(op.f('ix_historial_flujo_id_historial'), 'historial_flujo', ['id_historial'], unique=False)
    op.drop_constraint(op.f('fk_historial_flujo_misiones'), 'historial_flujo', type_='foreignkey')
    op.create_foreign_key(None, 'historial_flujo', 'estados_flujo', ['id_estado_anterior'], ['id_estado_flujo'])
    op.create_foreign_key(None, 'historial_flujo', 'misiones', ['id_mision'], ['id_mision'])
    op.drop_table_comment(
        'historial_flujo',
        existing_comment='Auditoría completa de todas las acciones',
        schema=None
    )
    op.alter_column('items_transporte', 'tipo',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='Terrestre, Aéreo, Marítimo',
               existing_nullable=False)
    op.drop_index(op.f('fk_items_transporte_misiones_idx'), table_name='items_transporte')
    op.drop_index(op.f('idx_tipo'), table_name='items_transporte')
    op.create_index(op.f('ix_items_transporte_id_item_transporte'), 'items_transporte', ['id_item_transporte'], unique=False)
    op.drop_constraint(op.f('fk_items_transporte_misiones'), 'items_transporte', type_='foreignkey')
    op.create_foreign_key(None, 'items_transporte', 'misiones', ['id_mision'], ['id_mision'])
    op.drop_table_comment(
        'items_transporte',
        existing_comment='Detalle de los tramos de transporte de una misión',
        schema=None
    )
    op.drop_index(op.f('fk_items_viaticos_misiones_idx'), table_name='items_viaticos')
    op.drop_index(op.f('idx_fecha'), table_name='items_viaticos')
    op.create_index(op.f('ix_items_viaticos_id_item_viatico'), 'items_viaticos', ['id_item_viatico'], unique=False)
    op.drop_constraint(op.f('fk_items_viaticos_misiones'), 'items_viaticos', type_='foreignkey')
    op.create_foreign_key(None, 'items_viaticos', 'misiones', ['id_mision'], ['id_mision'])
    op.drop_table_comment(
        'items_viaticos',
        existing_comment='Detalle de gastos de alimentación y hospedaje por día',
        schema=None
    )
    op.alter_column('misiones', 'solicitud_caso_id_rrhh',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='FK al ID en aitsa_rrhh.solicitudes_casos',
               existing_nullable=False)
    op.alter_column('misiones', 'tipo_mision',
               existing_type=mysql.ENUM('VIATICOS', 'CAJA_MENUDA'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('misiones', 'beneficiario_personal_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='ID del empleado en aitsa_rrhh.nompersonal',
               existing_nullable=False)
    op.alter_column('misiones', 'monto_aprobado',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='Monto final aprobado, puede diferir del calculado',
               existing_nullable=True)
    op.alter_column('misiones', 'requiere_refrendo_cgr',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='Si requiere refrendo de Contraloría',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('misiones', 'numero_gestion_cobro',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='Número de la gestión de cobro generada',
               existing_nullable=True)
    op.alter_column('misiones', 'fecha_limite_presentacion',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Fecha límite para presentar documentos (10 días)',
               existing_nullable=True)
    op.drop_index(op.f('fk_misiones_estados_flujo_idx'), table_name='misiones')
    op.drop_index(op.f('idx_beneficiario'), table_name='misiones')
    op.drop_index(op.f('idx_fecha_salida'), table_name='misiones')
    op.drop_index(op.f('idx_tipo_mision'), table_name='misiones')
    op.create_index(op.f('ix_misiones_id_mision'), 'misiones', ['id_mision'], unique=False)
    op.drop_constraint(op.f('fk_misiones_estados_flujo'), 'misiones', type_='foreignkey')
    op.create_foreign_key(None, 'misiones', 'estados_flujo', ['id_estado_flujo'], ['id_estado_flujo'])
    op.drop_table_comment(
        'misiones',
        existing_comment='Registro maestro para cada misión oficial',
        schema=None
    )
    op.alter_column('roles', 'nombre_rol',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='Solicitante, Jefe Inmediato, Analista Tesorería, Custodio Caja Menuda, Analista Presupuesto, Analista Contabilidad, Director Finanzas, Fiscalizador CGR',
               existing_nullable=False)
    op.alter_column('roles', 'descripcion',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='Descripción detallada de las responsabilidades del rol',
               existing_nullable=True)
    op.alter_column('roles', 'permisos_json',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='Permisos específicos en formato JSON para flexibilidad futura',
               existing_nullable=True)
    op.alter_column('roles', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_roles_id_rol'), 'roles', ['id_rol'], unique=False)
    op.drop_table_comment(
        'roles',
        existing_comment='Roles de usuario para el sistema financiero de misiones',
        schema=None
    )
    op.alter_column('subsanaciones', 'id_usuario_solicita',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Usuario que solicita la subsanación',
               existing_nullable=False)
    op.alter_column('subsanaciones', 'id_usuario_responsable',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Usuario responsable de corregir',
               existing_nullable=False)
    op.alter_column('subsanaciones', 'fecha_solicitud',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('subsanaciones', 'fecha_respuesta',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('subsanaciones', 'estado',
               existing_type=mysql.ENUM('PENDIENTE', 'COMPLETADA', 'VENCIDA'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDIENTE'"))
    op.drop_index(op.f('fk_subsanaciones_misiones_idx'), table_name='subsanaciones')
    op.drop_index(op.f('fk_subsanaciones_responsable_idx'), table_name='subsanaciones')
    op.drop_index(op.f('fk_subsanaciones_solicita_idx'), table_name='subsanaciones')
    op.drop_index(op.f('idx_estado'), table_name='subsanaciones')
    op.create_index(op.f('ix_subsanaciones_id_subsanacion'), 'subsanaciones', ['id_subsanacion'], unique=False)
    op.drop_constraint(op.f('fk_subsanaciones_misiones'), 'subsanaciones', type_='foreignkey')
    op.create_foreign_key(None, 'subsanaciones', 'misiones', ['id_mision'], ['id_mision'])
    op.drop_table_comment(
        'subsanaciones',
        existing_comment='Gestión de subsanaciones y devoluciones para corrección',
        schema=None
    )
    op.alter_column('transiciones_flujo', 'tipo_accion',
               existing_type=mysql.ENUM('APROBAR', 'RECHAZAR', 'DEVOLVER', 'SUBSANAR'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index(op.f('fk_transiciones_estado_destino_idx'), table_name='transiciones_flujo')
    op.drop_index(op.f('fk_transiciones_estado_origen_idx'), table_name='transiciones_flujo')
    op.drop_index(op.f('fk_transiciones_rol_idx'), table_name='transiciones_flujo')
    op.drop_index(op.f('unique_transicion'), table_name='transiciones_flujo')
    op.create_index(op.f('ix_transiciones_flujo_id_transicion'), 'transiciones_flujo', ['id_transicion'], unique=False)
    op.drop_table_comment(
        'transiciones_flujo',
        existing_comment='Matriz de transiciones válidas entre estados según roles',
        schema=None
    )
    op.alter_column('usuarios', 'personal_id_rrhh',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='FK a aitsa_rrhh.nompersonal.personal_id')
    op.alter_column('usuarios', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='Hash bcrypt de la contraseña',
               existing_nullable=False)
    op.alter_column('usuarios', 'ultimo_acceso',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('fk_usuarios_roles_idx'), table_name='usuarios')
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    op.drop_constraint(op.f('fk_usuarios_roles'), 'usuarios', type_='foreignkey')
    op.create_foreign_key(None, 'usuarios', 'roles', ['id_rol'], ['id_rol'])
    op.drop_table_comment(
        'usuarios',
        existing_comment='Usuarios con acceso al sistema de gestión de misiones',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'usuarios',
        'Usuarios con acceso al sistema de gestión de misiones',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.create_foreign_key(op.f('fk_usuarios_roles'), 'usuarios', 'roles', ['id_rol'], ['id_rol'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.create_index(op.f('fk_usuarios_roles_idx'), 'usuarios', ['id_rol'], unique=False)
    op.alter_column('usuarios', 'ultimo_acceso',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('usuarios', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               comment='Hash bcrypt de la contraseña',
               existing_nullable=False)
    op.alter_column('usuarios', 'personal_id_rrhh',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='FK a aitsa_rrhh.nompersonal.personal_id')
    op.create_table_comment(
        'transiciones_flujo',
        'Matriz de transiciones válidas entre estados según roles',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_transiciones_flujo_id_transicion'), table_name='transiciones_flujo')
    op.create_index(op.f('unique_transicion'), 'transiciones_flujo', ['id_estado_origen', 'id_estado_destino', 'id_rol_autorizado', 'tipo_accion'], unique=True)
    op.create_index(op.f('fk_transiciones_rol_idx'), 'transiciones_flujo', ['id_rol_autorizado'], unique=False)
    op.create_index(op.f('fk_transiciones_estado_origen_idx'), 'transiciones_flujo', ['id_estado_origen'], unique=False)
    op.create_index(op.f('fk_transiciones_estado_destino_idx'), 'transiciones_flujo', ['id_estado_destino'], unique=False)
    op.alter_column('transiciones_flujo', 'tipo_accion',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('APROBAR', 'RECHAZAR', 'DEVOLVER', 'SUBSANAR'),
               existing_nullable=False)
    op.create_table_comment(
        'subsanaciones',
        'Gestión de subsanaciones y devoluciones para corrección',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'subsanaciones', type_='foreignkey')
    op.create_foreign_key(op.f('fk_subsanaciones_misiones'), 'subsanaciones', 'misiones', ['id_mision'], ['id_mision'], ondelete='CASCADE')
    op.drop_index(op.f('ix_subsanaciones_id_subsanacion'), table_name='subsanaciones')
    op.create_index(op.f('idx_estado'), 'subsanaciones', ['estado'], unique=False)
    op.create_index(op.f('fk_subsanaciones_solicita_idx'), 'subsanaciones', ['id_usuario_solicita'], unique=False)
    op.create_index(op.f('fk_subsanaciones_responsable_idx'), 'subsanaciones', ['id_usuario_responsable'], unique=False)
    op.create_index(op.f('fk_subsanaciones_misiones_idx'), 'subsanaciones', ['id_mision'], unique=False)
    op.alter_column('subsanaciones', 'estado',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('PENDIENTE', 'COMPLETADA', 'VENCIDA'),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDIENTE'"))
    op.alter_column('subsanaciones', 'fecha_respuesta',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('subsanaciones', 'fecha_solicitud',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('subsanaciones', 'id_usuario_responsable',
               existing_type=mysql.INTEGER(),
               comment='Usuario responsable de corregir',
               existing_nullable=False)
    op.alter_column('subsanaciones', 'id_usuario_solicita',
               existing_type=mysql.INTEGER(),
               comment='Usuario que solicita la subsanación',
               existing_nullable=False)
    op.create_table_comment(
        'roles',
        'Roles de usuario para el sistema financiero de misiones',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_roles_id_rol'), table_name='roles')
    op.alter_column('roles', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('roles', 'permisos_json',
               existing_type=mysql.JSON(),
               comment='Permisos específicos en formato JSON para flexibilidad futura',
               existing_nullable=True)
    op.alter_column('roles', 'descripcion',
               existing_type=mysql.TEXT(),
               comment='Descripción detallada de las responsabilidades del rol',
               existing_nullable=True)
    op.alter_column('roles', 'nombre_rol',
               existing_type=mysql.VARCHAR(length=100),
               comment='Solicitante, Jefe Inmediato, Analista Tesorería, Custodio Caja Menuda, Analista Presupuesto, Analista Contabilidad, Director Finanzas, Fiscalizador CGR',
               existing_nullable=False)
    op.create_table_comment(
        'misiones',
        'Registro maestro para cada misión oficial',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'misiones', type_='foreignkey')
    op.create_foreign_key(op.f('fk_misiones_estados_flujo'), 'misiones', 'estados_flujo', ['id_estado_flujo'], ['id_estado_flujo'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_misiones_id_mision'), table_name='misiones')
    op.create_index(op.f('idx_tipo_mision'), 'misiones', ['tipo_mision'], unique=False)
    op.create_index(op.f('idx_fecha_salida'), 'misiones', ['fecha_salida'], unique=False)
    op.create_index(op.f('idx_beneficiario'), 'misiones', ['beneficiario_personal_id'], unique=False)
    op.create_index(op.f('fk_misiones_estados_flujo_idx'), 'misiones', ['id_estado_flujo'], unique=False)
    op.alter_column('misiones', 'fecha_limite_presentacion',
               existing_type=sa.DATE(),
               comment='Fecha límite para presentar documentos (10 días)',
               existing_nullable=True)
    op.alter_column('misiones', 'numero_gestion_cobro',
               existing_type=mysql.VARCHAR(length=50),
               comment='Número de la gestión de cobro generada',
               existing_nullable=True)
    op.alter_column('misiones', 'requiere_refrendo_cgr',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Si requiere refrendo de Contraloría',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('misiones', 'monto_aprobado',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='Monto final aprobado, puede diferir del calculado',
               existing_nullable=True)
    op.alter_column('misiones', 'beneficiario_personal_id',
               existing_type=mysql.INTEGER(),
               comment='ID del empleado en aitsa_rrhh.nompersonal',
               existing_nullable=False)
    op.alter_column('misiones', 'tipo_mision',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('VIATICOS', 'CAJA_MENUDA'),
               existing_nullable=False)
    op.alter_column('misiones', 'solicitud_caso_id_rrhh',
               existing_type=mysql.INTEGER(),
               comment='FK al ID en aitsa_rrhh.solicitudes_casos',
               existing_nullable=False)
    op.create_table_comment(
        'items_viaticos',
        'Detalle de gastos de alimentación y hospedaje por día',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'items_viaticos', type_='foreignkey')
    op.create_foreign_key(op.f('fk_items_viaticos_misiones'), 'items_viaticos', 'misiones', ['id_mision'], ['id_mision'], ondelete='CASCADE')
    op.drop_index(op.f('ix_items_viaticos_id_item_viatico'), table_name='items_viaticos')
    op.create_index(op.f('idx_fecha'), 'items_viaticos', ['fecha'], unique=False)
    op.create_index(op.f('fk_items_viaticos_misiones_idx'), 'items_viaticos', ['id_mision'], unique=False)
    op.create_table_comment(
        'items_transporte',
        'Detalle de los tramos de transporte de una misión',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'items_transporte', type_='foreignkey')
    op.create_foreign_key(op.f('fk_items_transporte_misiones'), 'items_transporte', 'misiones', ['id_mision'], ['id_mision'], ondelete='CASCADE')
    op.drop_index(op.f('ix_items_transporte_id_item_transporte'), table_name='items_transporte')
    op.create_index(op.f('idx_tipo'), 'items_transporte', ['tipo'], unique=False)
    op.create_index(op.f('fk_items_transporte_misiones_idx'), 'items_transporte', ['id_mision'], unique=False)
    op.alter_column('items_transporte', 'tipo',
               existing_type=mysql.VARCHAR(length=50),
               comment='Terrestre, Aéreo, Marítimo',
               existing_nullable=False)
    op.create_table_comment(
        'historial_flujo',
        'Auditoría completa de todas las acciones',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'historial_flujo', type_='foreignkey')
    op.drop_constraint(None, 'historial_flujo', type_='foreignkey')
    op.create_foreign_key(op.f('fk_historial_flujo_misiones'), 'historial_flujo', 'misiones', ['id_mision'], ['id_mision'], ondelete='CASCADE')
    op.drop_index(op.f('ix_historial_flujo_id_historial'), table_name='historial_flujo')
    op.create_index(op.f('idx_fecha_accion'), 'historial_flujo', ['fecha_accion'], unique=False)
    op.create_index(op.f('fk_historial_flujo_usuarios_idx'), 'historial_flujo', ['id_usuario_accion'], unique=False)
    op.create_index(op.f('fk_historial_flujo_misiones_idx'), 'historial_flujo', ['id_mision'], unique=False)
    op.create_index(op.f('fk_historial_flujo_estado_nuevo_idx'), 'historial_flujo', ['id_estado_nuevo'], unique=False)
    op.alter_column('historial_flujo', 'datos_adicionales',
               existing_type=mysql.JSON(),
               comment='Información adicional de la acción en formato JSON',
               existing_nullable=True)
    op.alter_column('historial_flujo', 'fecha_accion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('historial_flujo', 'tipo_accion',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('APROBAR', 'RECHAZAR', 'DEVOLVER', 'SUBSANAR', 'CREAR', 'MODIFICAR'),
               existing_nullable=False)
    op.create_table_comment(
        'gestiones_cobro',
        'Gestiones de cobro generadas por Tesorería',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'gestiones_cobro', type_='foreignkey')
    op.create_foreign_key(op.f('fk_gestiones_misiones'), 'gestiones_cobro', 'misiones', ['id_mision'], ['id_mision'], ondelete='CASCADE')
    op.drop_index(op.f('ix_gestiones_cobro_id_gestion_cobro'), table_name='gestiones_cobro')
    op.create_index(op.f('fk_gestiones_usuarios_idx'), 'gestiones_cobro', ['id_usuario_genero'], unique=False)
    op.alter_column('gestiones_cobro', 'estado',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('PENDIENTE', 'EN_PROCESO', 'COMPLETADA', 'ANULADA'),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDIENTE'"))
    op.alter_column('gestiones_cobro', 'fecha_generacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('gestiones_cobro', 'numero_gestion',
               existing_type=mysql.VARCHAR(length=50),
               comment='Número único de la gestión de cobro',
               existing_nullable=False)
    op.create_table_comment(
        'estados_flujo',
        'Estados del ciclo de vida de una misión oficial',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_estados_flujo_id_estado_flujo'), table_name='estados_flujo')
    op.alter_column('estados_flujo', 'tipo_flujo',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('VIATICOS', 'CAJA_MENUDA', 'AMBOS'),
               existing_nullable=False,
               existing_server_default=sa.text("'AMBOS'"))
    op.alter_column('estados_flujo', 'orden_flujo',
               existing_type=mysql.INTEGER(),
               comment='Orden secuencial en el flujo normal',
               existing_nullable=True)
    op.alter_column('estados_flujo', 'requiere_comentario',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Si requiere comentario obligatorio al cambiar a este estado',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('estados_flujo', 'es_estado_final',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Indica si es un estado terminal del flujo',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.create_table_comment(
        'configuraciones_sistema',
        'Configuraciones globales del sistema (límites, tarifas, etc.)',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_configuraciones_sistema_id_configuracion'), table_name='configuraciones_sistema')
    op.alter_column('configuraciones_sistema', 'es_modificable',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('configuraciones_sistema', 'tipo_dato',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('STRING', 'NUMBER', 'BOOLEAN', 'JSON'),
               nullable=False,
               existing_server_default=sa.text("'STRING'"))
    op.drop_index(op.f('ix_configuraciones_general_id_configuracion_general'), table_name='configuraciones_general')
    op.alter_column('configuraciones_general', 'smtp_seguridad',
               existing_type=sa.String(length=10),
               type_=mysql.ENUM('none', 'tls', 'ssl', collation='utf8mb4_general_ci'),
               existing_nullable=True,
               existing_server_default=sa.text("'tls'"))
    op.create_table_comment(
        'adjuntos',
        'Archivos de soporte para las misiones',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'adjuntos', type_='foreignkey')
    op.create_foreign_key(op.f('fk_adjuntos_misiones'), 'adjuntos', 'misiones', ['id_mision'], ['id_mision'], ondelete='CASCADE')
    op.drop_index(op.f('ix_adjuntos_id_adjunto'), table_name='adjuntos')
    op.create_index(op.f('fk_adjuntos_usuarios_idx'), 'adjuntos', ['id_usuario_subio'], unique=False)
    op.create_index(op.f('fk_adjuntos_misiones_idx'), 'adjuntos', ['id_mision'], unique=False)
    op.alter_column('adjuntos', 'fecha_carga',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('adjuntos', 'tipo_documento',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('SOLICITUD', 'COMPROBANTE', 'FACTURA', 'OTRO'),
               existing_nullable=False,
               existing_server_default=sa.text("'OTRO'"))
    # ### end Alembic commands ###
